// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9I_k611wndLWmNd-oX1i4Qdl_Vg4jf8',
    appId: '1:735163409376:web:fffa17dd2260d079720185',
    messagingSenderId: '735163409376',
    projectId: 'assignment-87abf',
    authDomain: 'assignment-87abf.firebaseapp.com',
    storageBucket: 'assignment-87abf.appspot.com',
    measurementId: 'G-3Y0PYM658J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMWTAGQZK1PpWu0PJj4hX27QvHM6RGfR0',
    appId: '1:735163409376:android:9cef424a2f99a608720185',
    messagingSenderId: '735163409376',
    projectId: 'assignment-87abf',
    storageBucket: 'assignment-87abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEusX2HZZAZYY128tgxODlSsIe7hZm2xU',
    appId: '1:735163409376:ios:26f65bf11dbf411d720185',
    messagingSenderId: '735163409376',
    projectId: 'assignment-87abf',
    storageBucket: 'assignment-87abf.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEusX2HZZAZYY128tgxODlSsIe7hZm2xU',
    appId: '1:735163409376:ios:a0f364b629d0e856720185',
    messagingSenderId: '735163409376',
    projectId: 'assignment-87abf',
    storageBucket: 'assignment-87abf.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
